### PR TITLE
Portfolio Mockup

### PR DESCRIPTION
**Pull request by SaveryIV**
This is the second project in Microverse:

   -Added CSS styles.
   -Added HTML code.
   -Added linters.

### CODE REVIEW

**Review by iambenkis — COMMENTED** [review]
Hi @SaveryIV  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that has linters that do not pass, make sure you solve them and to ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by GedeonTS — CHANGES_REQUESTED** [review]
# INVALID REVIEW REQUEST

Hi @SaveryIV , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not documented, and does not have a Readme File. You can Add  adescriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Yerimah — CHANGES_REQUESTED** [review]
# STATUS: INVALID CODE REQUEST 🔴  

Hi @SaveryIV, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a Readme File. You can Add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by ABDULALI3468 — CHANGES_REQUESTED** [review]
# Changes Required 👍 

Hi @SaveryIV , 



Indeed you did an exceptional but still, there is room for changes to complete this project. 💯


## Highlights 
✅All linters are checked.
✅Project is professionally documented.


 ## Required Changes ♻️

As you did not change anything n the index.html file so I will not be able to make inline comments but will try to make them clear to you how much I can 🙇‍♂️ 

**1-** Please consider using a link (a tag) for the [logo](
https://github.com/SaveryIV/Portfolio-Responsive/blob/e2a4834493b33042f10b635763ce041355dedbce/index.html#L12) in the header rather than the `p tag`

This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

**2A-** The main [title](https://github.com/SaveryIV/Portfolio-Responsive/blob/e2a4834493b33042f10b635763ce041355dedbce/index.html#L20) (e.g., "  I’m Agustin ...") needs to be an `h1` tag.

* If you want that google (and other search engines) to know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. The main title (e.g., "I'm Marianne ...") is a h1 tag.

If you want that google (and other search engines) knows about a specific topic, in this case, you, use an h1 tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

**2B-** Please consider using the same styles as used in the Figma template to meet the project requirements. Currently, there is a `letter spacing` in your headline but in styles, there is no letter spacing. Kindly consider removing this [property](https://github.com/SaveryIV/Portfolio-Responsive/blob/e2a4834493b33042f10b635763ce041355dedbce/style.css#L76).

**3-** The [button](https://github.com/SaveryIV/Portfolio-Responsive/blob/e2a4834493b33042f10b635763ce041355dedbce/index.html#L33) needs to be an `a or button tag` to make it semantically correct and to meet the project requirements.

Apart from being semantically correct, the `a tag` will let you connect to other sections of the website, using href.

**4-** The list of [icons](https://github.com/SaveryIV/Portfolio-Responsive/blob/e2a4834493b33042f10b635763ce041355dedbce/index.html#L34) needs to use a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag).

* Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

### FOR BETTER UNDERSTANDING OF ABOVE:-

```
 <ul class="span">
      <li>
        <a href="https://ar.twitter.com/">
          <img src="./resources/icons/Vectoricons-3.svg" alt="Twitter" class="social-media" />
        </a>
      </li>

      <li>
        <a href="https://ar.linkedin.com/"><img src="./resources/icons/Linkedin iconicons.svg" alt="Linkedin" class="social-media" /></a>
      </li>

      <li>
        <a href="https://medium.com/">
          <img src="./resources/icons/Vectoricons-1.svg" alt="Medium" class="social-media" />
        </a>
      </li>

      <li>
        <a href="https://github.com/"><img src="./resources/icons/Vectoricons-2.svg" alt="GitHub" class="social-media" /></a>
      </li>

      <li>
        <a href="index.html" target="_self"><img src="./resources/icons/Vectoricons.svg" alt="¿?" class="social-media" /></a>
      </li>
    </ul>
```


**5-** The background images used in the design are not showing in the headline section at the bottom of it please consider removing them for more clarity I am attaching a screenshot of images to better describe what I am talking about.

### FIGMA DESIGN:-

image

### YOUR DESIGN:-

image


**6-** There are multiple problems of semantics throughout the design that's why for better convenience I am presenting you a better semantically correct code to use main and section tags so please consider correcting them also.

```

    <header>
      <a href="/" class="logo">MY LOGO</a>
      <nav>
        <img src="./hamburgericon.png" alt="">
      </nav>
    </header>

    <main>
      <section class="headline-section">
        CONTENT RELATED TO HEADLINE
      </section>
      <section class="work-section">
        CONTENT RELATED TO WORK
      </section>
    </main>

    <footer></footer>
```

> NO USE OF ARTICLE TAG INSIDE SECTION TAG HERE ✅ 




## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: GitHub followers
> * This is My **Linkedin**: [Linkedin Badge](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [Twitter Badge](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ABDULALI3468** [comment]
@SaveryIV I saw from last 8 hours you are seeing invalidation messages only that's why I stopped as its your almost first time but remember the name of your branch is also not professional.

Please consider always using the name of your feature branch as a way to highlight what you did in it (e.g. 'created_sidebar' or 'added_comments_section')  In this case, your branch name is `feature` which is not professional.

> You can name it `feature-1/mobile-toolbar-headline-section` or something else that describes what you did in the branch.

**Review by GedeonTS — APPROVED** [review]
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @SaveryIV ,

Your are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

 

## Highlights :clap: :tophat: 
- Linters are Passing :+1: 
- Meaningful commit messages :+1: 

## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
